SELECT USER 
FROM DUAL;

--○ 실습 테이블 생성
CREATE TABLE TBL_SCORE
( SID NUMBER
, NAME VARCHAR2(30)
, KOR NUMBER(3)
, ENG NUMBER(3)
, MAT NUMBER(3)
);
--==>> Table TBL_SCORE이(가) 생성되었습니다.

-- 제약조건 추가 
ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_SID_PK PRIMARY KEY(SID);
--==>> Table TBL_SCORE이(가) 변경되었습니다.

--○ 제약조건 추가 (KOR, ENG, MAT 컬럼에 CK 제약조건 추가)
ALTER TABLE TBL_SCORE
ADD( CONSTRAINT SCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100)
   , CONSTRAINT SCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100)
   , CONSTRAINT SCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100) );
--==>> Table TBL_SCORE이(가) 변경되었습니다


INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES (SCORESEQ.NEXTVAL,'박원석', 80, 70, 85)
;

SELECT SID"번호", NAME"이름", KOR"국어", ENG"영어", MAT"수학",KOR+ENG+MAT "총점", (KOR+ENG+MAT)/ 3"평균" 
FROM TBL_SCORE
ORDER BY 1 ;


SELECT SID , NAME, KOR , ENG, MAT , KOR+ENG+MAT AS SUM, (KOR+ENG+MAT)/ 3 AS AVG FROM TBL_SCORE ORDER BY 1 
;

SELECT COUNT(*) AS COUNT FROM TBL_Score
;

SELECT *
FROM TBL_SCORE;


SELECT sid, NAME
FROM TBL_Score;

CREATE SEQUENCE SCORESEQ
NOCACHE;
--==>> Sequence SCORESEQ이(가) 생성되었습니다.

